# Generated by Django 5.2.5 on 2025-08-26 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('COORDINATOR', 'Coordinator'), ('ADMIN', 'Admin')], default='STUDENT', max_length=20),
        ),
    ]
