# Generated by Django 5.2.5 on 2025-08-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('users', '0003_customuser_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='coordinated_titulaciones',
            field=models.ManyToManyField(blank=True, to='academics.titulacion'),
        ),
    ]
