# Generated by Django 5.2.5 on 2025-08-30 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(help_text='Código único para usar en el código (ej: STUDENT, TEACHER)', max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del perfil y sus permisos')),
                ('color', models.CharField(default='#6c757d', help_text='Color para badges en formato hex (#ffffff)', max_length=7)),
                ('icono', models.CharField(default='bi-person', help_text='Icono Bootstrap Icons (ej: bi-person, bi-gear)', max_length=50)),
                ('permisos', models.JSONField(blank=True, default=dict, help_text='Configuración de permisos en formato JSON')),
                ('es_sistema', models.BooleanField(default=False, help_text='Los perfiles del sistema no se pueden eliminar')),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Orden de aparición en interfaces')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Perfil',
                'verbose_name_plural': 'Tipos de Perfil',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='AsignacionPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True, help_text='Notas opcionales sobre esta asignación')),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('asignado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_realizadas', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_perfil', to=settings.AUTH_USER_MODEL)),
                ('tipo_perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='users.tipoperfil')),
            ],
            options={
                'verbose_name': 'Asignación de Perfil',
                'verbose_name_plural': 'Asignaciones de Perfil',
                'ordering': ['-fecha_asignacion'],
                'unique_together': {('usuario', 'tipo_perfil')},
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='tipos_perfil',
            field=models.ManyToManyField(blank=True, through='users.AsignacionPerfil', through_fields=('usuario', 'tipo_perfil'), to='users.tipoperfil'),
        ),
    ]
