# Generated by Django 5.2.5 on 2026-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_spanish_ui_labels'),
        ('users', '0007_populate_initial_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionperfil',
            options={'ordering': ['-fecha_asignacion'], 'verbose_name': 'asignación de perfil', 'verbose_name_plural': 'asignaciones de perfil'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='loginattempt',
            options={'verbose_name': 'intento de inicio de sesión', 'verbose_name_plural': 'intentos de inicio de sesión'},
        ),
        migrations.AlterModelOptions(
            name='tipoperfil',
            options={'ordering': ['orden', 'nombre'], 'verbose_name': 'tipo de perfil', 'verbose_name_plural': 'tipos de perfil'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='coordinated_titulaciones',
            field=models.ManyToManyField(blank=True, to='academics.titulacion', verbose_name='titulaciones coordinadas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Estudiante'), ('TEACHER', 'Profesor/a'), ('COORDINATOR', 'Coordinador/a'), ('ADMIN', 'Administrador/a')], default='STUDENT', max_length=20, verbose_name='rol'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='academics.asignatura', verbose_name='asignaturas'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tipos_perfil',
            field=models.ManyToManyField(blank=True, through='users.AsignacionPerfil', through_fields=('usuario', 'tipo_perfil'), to='users.tipoperfil', verbose_name='tipos de perfil'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='dirección IP'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='success',
            field=models.BooleanField(verbose_name='correcto'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='loginattempt',
            name='username',
            field=models.CharField(max_length=150, verbose_name='nombre de usuario'),
        ),
        migrations.AlterField(
            model_name='tipoperfil',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='tipoperfil',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de actualización'),
        ),
    ]
