# Generated by Django 5.2.5 on 2025-08-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('schedule', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='actividad',
            name='asignaturas',
            field=models.ManyToManyField(to='academics.asignatura'),
        ),
    ]
