# Generated by Django 5.2.6 on 2025-09-10 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0006_add_activity_versioning"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="actividadversion",
            name="unique_activity_version",
        ),
        migrations.AddField(
            model_name="actividad",
            name="grupo_id",
            field=models.UUIDField(
                blank=True,
                help_text="Identificador para agrupar actividades de múltiples grupos",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="actividadversion",
            unique_together={("actividad_original", "version_numero")},
        ),
    ]
