# Generated by Django 5.2.5 on 2025-09-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_actividadversion_unique_activity_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='grupo_id',
            field=models.UUIDField(blank=True, help_text='Identificador para agrupar actividades de múltiples grupos - DEPRECATED', null=True),
        ),
    ]
