# Generated by Django 5.2.5 on 2025-09-16 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_remove_actividadversion_unique_activity_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='grupo_id',
            field=models.UUIDField(blank=True, help_text='Identificador para agrupar actividades de múltiples grupos - DEPRECATED', null=True),
        ),
        migrations.CreateModel(
            name='ActividadGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(help_text="Nombre del grupo (ej: 'A', 'B', 'Mañana', '1')", max_length=100)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del grupo (instrucciones específicas, etc.)', null=True)),
                ('lugar', models.CharField(blank=True, help_text='Lugar donde se realiza el grupo (aula, laboratorio, etc.)', max_length=255, null=True)),
                ('orden', models.PositiveIntegerField(default=1, help_text='Orden de visualización de los grupos')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='schedule.actividad')),
            ],
            options={
                'verbose_name': 'Grupo de Actividad',
                'verbose_name_plural': 'Grupos de Actividades',
                'ordering': ['orden', 'fecha_inicio'],
                'unique_together': {('actividad', 'nombre_grupo')},
            },
        ),
    ]
