# Generated by Django 5.2.6 on 2025-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0008_add_actividadgrupo_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="actividadgrupo",
            name="lugar",
            field=models.CharField(
                blank=True,
                help_text="Lugar donde se realiza el grupo (aula, laboratorio, etc.)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="actividadgrupo",
            name="descripcion",
            field=models.TextField(
                blank=True,
                help_text="Descripción del grupo (instrucciones específicas, etc.)",
                null=True,
            ),
        ),
    ]
