# Generated by Django 5.2.5 on 2025-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0008_alter_actividad_grupo_id_actividadgrupo'),
        ('schedule', '0009_actividadgrupo_lugar_and_more'),
    ]

    operations = [
    ]
