# Generated by Django 5.2.5 on 2025-09-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0010_merge_20250916_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.CharField(choices=[('visible', 'Visible'), ('borrada', 'Borrada'), ('archivada', 'Archivada')], default='visible', help_text='Estado actual de la actividad', max_length=20),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='activa',
            field=models.BooleanField(default=True, help_text="LEGACY: Usar campo 'estado' en su lugar"),
        ),
    ]
