# Generated by Django 5.2.5 on 2026-09-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_spanish_ui_labels'),
        ('schedule', '0015_import_uniqueness_ignores_deleted_copies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'actividad', 'verbose_name_plural': 'actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadgrupo',
            options={'ordering': ['orden', 'fecha_inicio'], 'verbose_name': 'grupo de actividad', 'verbose_name_plural': 'grupos de actividades'},
        ),
        migrations.AlterModelOptions(
            name='actividadversion',
            options={'ordering': ['-fecha_modificacion'], 'verbose_name': 'versión de actividad', 'verbose_name_plural': 'versiones de actividad'},
        ),
        migrations.AlterModelOptions(
            name='logactividad',
            options={'ordering': ['-timestamp'], 'verbose_name': 'registro de actividad', 'verbose_name_plural': 'registros de actividad'},
        ),
        migrations.AlterModelOptions(
            name='tipoactividad',
            options={'verbose_name': 'tipo de actividad', 'verbose_name_plural': 'tipos de actividad'},
        ),
        migrations.AlterModelOptions(
            name='vistacalendario',
            options={'verbose_name': 'calendario', 'verbose_name_plural': 'calendarios'},
        ),
        migrations.AlterField(
            model_name='actividad',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activities', to='academics.academicyear', verbose_name='curso académico'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='copied_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='schedule.actividad', verbose_name='copiada de'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_fin',
            field=models.DateTimeField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='fecha_inicio',
            field=models.DateTimeField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='porcentaje_evaluacion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='porcentaje de evaluación'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tipo_actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.tipoactividad', verbose_name='tipo de actividad'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='details',
            field=models.TextField(blank=True, null=True, verbose_name='detalles'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='id del objeto'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='object_name',
            field=models.CharField(max_length=255, verbose_name='nombre del objeto'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='object_type',
            field=models.CharField(choices=[('actividad', 'Actividad'), ('tipo_actividad', 'Tipo de actividad'), ('coordinador', 'Asignación de coordinador')], default='actividad', max_length=20, verbose_name='tipo de objeto'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora'),
        ),
        migrations.AlterField(
            model_name='logactividad',
            name='tipo_log',
            field=models.CharField(max_length=50, verbose_name='tipo de registro'),
        ),
        migrations.AlterField(
            model_name='vistacalendario',
            name='tipos_actividad',
            field=models.ManyToManyField(to='schedule.tipoactividad', verbose_name='tipos de actividad'),
        ),
    ]
