# Generated by Django 5.2.5 on 2026-09-17 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_spanish_ui_labels'),
        ('schedule', '0016_spanish_ui_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IcalImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255, verbose_name='fichero de origen')),
                ('moodle_course_id', models.CharField(blank=True, max_length=64, verbose_name='identificador del curso en el campus virtual')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('state', models.CharField(choices=[('draft', 'Borrador'), ('applied', 'Aplicada')], default='draft', max_length=10, verbose_name='estado')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aplicación')),
            ],
            options={
                'verbose_name': 'importación de calendario',
                'verbose_name_plural': 'importaciones de calendario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IcalImportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=255, verbose_name='UID de iCalendar')),
                ('summary', models.CharField(max_length=255, verbose_name='resumen')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('starts_at', models.DateTimeField(verbose_name='fecha de inicio')),
                ('ends_at', models.DateTimeField(verbose_name='fecha de fin')),
                ('all_day', models.BooleanField(default=False, verbose_name='de día completo')),
                ('zero_duration', models.BooleanField(default=False, verbose_name='sin duración')),
                ('group_key', models.CharField(blank=True, max_length=255, verbose_name='clave de grupo')),
                ('selected', models.BooleanField(default=False, verbose_name='seleccionada')),
                ('evaluable', models.BooleanField(default=False, verbose_name='evaluable')),
                ('porcentaje_evaluacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='porcentaje de evaluación')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('created', 'Creada'), ('duplicate', 'Ya importada'), ('unsupported', 'No soportada'), ('error', 'Con error')], default='pending', max_length=12, verbose_name='estado')),
                ('status_detail', models.CharField(blank=True, max_length=255, verbose_name='detalle del estado')),
            ],
            options={
                'verbose_name': 'evento de importación de calendario',
                'verbose_name_plural': 'eventos de importación de calendario',
                'ordering': ['starts_at', 'uid'],
            },
        ),
        migrations.CreateModel(
            name='MoodleCourseSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moodle_course_id', models.CharField(max_length=64, unique=True, verbose_name='identificador del curso en el campus virtual')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
            ],
            options={
                'verbose_name': 'asignatura del curso del campus virtual',
                'verbose_name_plural': 'asignaturas de cursos del campus virtual',
                'ordering': ['moodle_course_id'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='ical_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='UID de iCalendar'),
        ),
        migrations.AddConstraint(
            model_name='actividad',
            constraint=models.UniqueConstraint(condition=models.Q(('ical_uid__isnull', False)), fields=('ical_uid', 'academic_year'), name='schedule_unique_ical_uid_per_year'),
        ),
        migrations.AddField(
            model_name='icalimport',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_imports', to='academics.academicyear', verbose_name='curso académico'),
        ),
        migrations.AddField(
            model_name='icalimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ical_imports', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AddField(
            model_name='icalimport',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ical_imports', to='academics.asignatura', verbose_name='asignatura'),
        ),
        migrations.AddField(
            model_name='icalimportevent',
            name='created_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.actividad', verbose_name='actividad creada'),
        ),
        migrations.AddField(
            model_name='icalimportevent',
            name='ical_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='schedule.icalimport', verbose_name='importación de calendario'),
        ),
        migrations.AddField(
            model_name='icalimportevent',
            name='tipo_actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='schedule.tipoactividad', verbose_name='tipo de actividad'),
        ),
        migrations.AddField(
            model_name='moodlecoursesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moodle_course_mappings', to='academics.asignatura', verbose_name='asignatura'),
        ),
        migrations.AddConstraint(
            model_name='icalimportevent',
            constraint=models.UniqueConstraint(fields=('ical_import', 'uid'), name='schedule_unique_ical_import_event'),
        ),
    ]
