# Generated by Django 5.2.5 on 2026-09-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda_academica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendasettings',
            options={'verbose_name': 'configuración de la agenda', 'verbose_name_plural': 'configuración de la agenda'},
        ),
        migrations.AlterField(
            model_name='agendasettings',
            name='closing_date',
            field=models.DateField(verbose_name='fecha de cierre'),
        ),
    ]
