# Generated by Django 5.2.5 on 2025-08-26 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('curso', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('titulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.titulacion')),
            ],
        ),
    ]
