# Generated by Django 5.2.5 on 2026-09-13 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_academicyear_subjectoffering_teachingassignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied')], default='draft', max_length=10)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_imports', to='academics.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogueImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_code', models.CharField(max_length=32)),
                ('plan_name', models.CharField(max_length=255)),
                ('subject_code', models.CharField(max_length=32)),
                ('subject_name', models.CharField(max_length=255)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('curricular_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('semester', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('match_status', models.CharField(choices=[('code', 'Matched by code'), ('name', 'Matched by name'), ('new', 'New')], default='new', max_length=10)),
                ('catalogue_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='academics.catalogueimport')),
                ('target_asignatura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.asignatura')),
                ('target_titulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.titulacion')),
            ],
            options={
                'ordering': ['plan_code', 'curricular_year', 'semester', 'subject_code'],
                'constraints': [models.UniqueConstraint(fields=('catalogue_import', 'plan_code', 'subject_code'), name='academics_unique_catalogue_import_row')],
            },
        ),
    ]
