# Generated by Django 5.2.5 on 2026-09-13 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_catalogue_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogueimportrow',
            name='plan_group',
            field=models.CharField(blank=True, help_text='Rows sharing this key land in the same Titulacion: "t:<pk>" or "new:<primary plan code>".', max_length=64),
        ),
        migrations.AddField(
            model_name='catalogueimportrow',
            name='plan_match_status',
            field=models.CharField(choices=[('code', 'Matched by code'), ('name', 'Matched by name'), ('new', 'New')], default='new', max_length=10),
        ),
        migrations.AddField(
            model_name='catalogueimportrow',
            name='plan_role',
            field=models.CharField(choices=[('primary', 'Primary plan code'), ('alias', 'Alias plan code')], default='primary', max_length=10),
        ),
        migrations.CreateModel(
            name='PlanCodeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('titulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_code_aliases', to='academics.titulacion')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
