# Generated by Django 5.2.5 on 2026-09-13 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_plan_code_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='match_status',
            field=models.CharField(choices=[('code', 'Matched by code'), ('name', 'Matched by name'), ('new', 'New'), ('manual', 'Manual mapping')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_match_status',
            field=models.CharField(choices=[('code', 'Matched by code'), ('name', 'Matched by name'), ('new', 'New'), ('manual', 'Manual mapping')], default='new', max_length=10),
        ),
        migrations.CreateModel(
            name='CatalogueImportPlanOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=32)),
                ('catalogue_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_overrides', to='academics.catalogueimport')),
                ('titulacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.titulacion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('catalogue_import', 'plan_code'), name='academics_unique_catalogue_plan_override')],
            },
        ),
    ]
