# Generated by Django 5.2.5 on 2026-09-15 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_catalogue_plan_override'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-starts_on'], 'verbose_name': 'curso académico', 'verbose_name_plural': 'cursos académicos'},
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'verbose_name': 'asignatura', 'verbose_name_plural': 'asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='catalogueimport',
            options={'ordering': ['-created_at'], 'verbose_name': 'importación de catálogo', 'verbose_name_plural': 'importaciones de catálogo'},
        ),
        migrations.AlterModelOptions(
            name='catalogueimportplanoverride',
            options={'verbose_name': 'asociación manual de plan', 'verbose_name_plural': 'asociaciones manuales de plan'},
        ),
        migrations.AlterModelOptions(
            name='catalogueimportrow',
            options={'ordering': ['plan_code', 'curricular_year', 'semester', 'subject_code'], 'verbose_name': 'fila de importación de catálogo', 'verbose_name_plural': 'filas de importación de catálogo'},
        ),
        migrations.AlterModelOptions(
            name='plancodealias',
            options={'ordering': ['code'], 'verbose_name': 'código de plan adicional', 'verbose_name_plural': 'códigos de plan adicionales'},
        ),
        migrations.AlterModelOptions(
            name='subjectoffering',
            options={'ordering': ['academic_year', 'subject__titulacion__nombre', 'curricular_year', 'semester', 'subject__nombre'], 'verbose_name': 'asignatura ofertada', 'verbose_name_plural': 'asignaturas ofertadas'},
        ),
        migrations.AlterModelOptions(
            name='teachingassignment',
            options={'verbose_name': 'asignación docente', 'verbose_name_plural': 'asignaciones docentes'},
        ),
        migrations.AlterModelOptions(
            name='titulacion',
            options={'verbose_name': 'titulación', 'verbose_name_plural': 'titulaciones'},
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='code',
            field=models.CharField(help_text='Ejemplo: 2026-27', max_length=9, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='ends_on',
            field=models.DateField(verbose_name='fecha de fin'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='starts_on',
            field=models.DateField(verbose_name='fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='state',
            field=models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activo'), ('archived', 'Archivado')], default='draft', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='codigo_asignatura',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='código de asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_subjects', to=settings.AUTH_USER_MODEL, verbose_name='coordinador/a'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.titulacion', verbose_name='titulación'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_imports', to='academics.academicyear', verbose_name='curso académico'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de aplicación'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalogue_imports', to=settings.AUTH_USER_MODEL, verbose_name='creada por'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, verbose_name='fichero de origen'),
        ),
        migrations.AlterField(
            model_name='catalogueimport',
            name='state',
            field=models.CharField(choices=[('draft', 'Borrador'), ('applied', 'Aplicada')], default='draft', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='catalogueimportplanoverride',
            name='catalogue_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_overrides', to='academics.catalogueimport', verbose_name='importación de catálogo'),
        ),
        migrations.AlterField(
            model_name='catalogueimportplanoverride',
            name='plan_code',
            field=models.CharField(max_length=32, verbose_name='código del plan'),
        ),
        migrations.AlterField(
            model_name='catalogueimportplanoverride',
            name='titulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.titulacion', verbose_name='titulación'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='catalogue_import',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='academics.catalogueimport', verbose_name='importación de catálogo'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='credits',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='créditos'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='curricular_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='line_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='número de línea'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='match_status',
            field=models.CharField(choices=[('code', 'Coincidencia por código'), ('name', 'Coincidencia por nombre'), ('new', 'Nueva'), ('manual', 'Asociación manual')], default='new', max_length=10, verbose_name='coincidencia de la asignatura'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_code',
            field=models.CharField(max_length=32, verbose_name='código del plan'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_group',
            field=models.CharField(blank=True, help_text='Las filas con esta misma clave se asignan a la misma titulación: "t:<pk>" o "new:<código del plan principal>".', max_length=64, verbose_name='grupo de planes'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_match_status',
            field=models.CharField(choices=[('code', 'Coincidencia por código'), ('name', 'Coincidencia por nombre'), ('new', 'Nueva'), ('manual', 'Asociación manual')], default='new', max_length=10, verbose_name='coincidencia del plan'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_name',
            field=models.CharField(max_length=255, verbose_name='nombre del plan'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='plan_role',
            field=models.CharField(choices=[('primary', 'Código de plan principal'), ('alias', 'Código de plan adicional')], default='primary', max_length=10, verbose_name='papel del código de plan'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='subject_code',
            field=models.CharField(max_length=32, verbose_name='código de asignatura'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='subject_name',
            field=models.CharField(max_length=255, verbose_name='nombre de la asignatura'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='target_asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.asignatura', verbose_name='asignatura de destino'),
        ),
        migrations.AlterField(
            model_name='catalogueimportrow',
            name='target_titulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='academics.titulacion', verbose_name='titulación de destino'),
        ),
        migrations.AlterField(
            model_name='plancodealias',
            name='code',
            field=models.CharField(max_length=32, unique=True, verbose_name='código'),
        ),
        migrations.AlterField(
            model_name='plancodealias',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='plancodealias',
            name='titulacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_code_aliases', to='academics.titulacion', verbose_name='titulación'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='academics.academicyear', verbose_name='curso académico'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='curricular_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='curso'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='semestre'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='state',
            field=models.CharField(choices=[('offered', 'Ofertada'), ('withdrawn', 'Retirada')], default='offered', max_length=10, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.asignatura', verbose_name='asignatura'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='activa'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='academics.subjectoffering', verbose_name='asignatura ofertada'),
        ),
        migrations.AlterField(
            model_name='teachingassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL, verbose_name='profesor/a'),
        ),
        migrations.AlterField(
            model_name='titulacion',
            name='codigo_plan',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='código del plan'),
        ),
    ]
